---
Name: SurveyManager
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs

SSViewer:
  # display template filenames as comments in the html output
  source_file_comments: true
  # This boilerplace suggests using only the mysite folder without a theme
  # if you want to set a theme, change the 2 lines below
  theme_enabled: false
  # theme: 'simple'